Repository ascopes/protobuf-maven-plugin, pull requests merged in 2024-08, with the labels that each got.

#323 Improve errors in AetherMavenArtifactPathResolver.java, remove duplicate code
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
Labels: internal improvement

#325 Simplify EnumSet usage in Language.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/Language.java
Labels: internal improvement

#326 Improve messages in SourceCodeGenerator.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceCodeGenerator.java
Labels: internal improvement

#328 Improve log output in AbstractGenerateMojo.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
Labels: internal improvement

#330 Update protobuf to 4.27.3
  README.md
  protobuf-maven-plugin/src/it/embed-main-sources/pom.xml
  protobuf-maven-plugin/src/it/gh-132-duplicate-maven-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-132-duplicate-maven-dependencies/some-project/pom.xml
  protobuf-maven-plugin/src/it/gh-135-compile-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-164-direct-dependency-resolution-depth-for-source-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-164-transitive-dependency-resolution-depth-for-source-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-250-excludes/pom.xml
  protobuf-maven-plugin/src/it/gh-250-includes/pom.xml
  protobuf-maven-plugin/src/it/gh-267-resolve-test-jar-type/pom.xml
  protobuf-maven-plugin/src/it/gh-267-resolve-tests-classifier/pom.xml
  protobuf-maven-plugin/src/it/gh-277-plugin-ordering/pom.xml
  protobuf-maven-plugin/src/it/gh-299-ehcache-jaxb-resolution-failure/pom.xml
  protobuf-maven-plugin/src/it/gh-302-runtime-scope-direct-resolution/pom.xml
  protobuf-maven-plugin/src/it/gh-302-runtime-scope-transitive-resolution/pom.xml
  protobuf-maven-plugin/src/it/grpc-plugin/pom.xml
  protobuf-maven-plugin/src/it/java-main-empty/pom.xml
  protobuf-maven-plugin/src/it/java-main-lite/pom.xml
  protobuf-maven-plugin/src/it/java-main/pom.xml
  protobuf-maven-plugin/src/it/java-paths/pom.xml
  protobuf-maven-plugin/src/it/java-test-empty/pom.xml
  protobuf-maven-plugin/src/it/java-test-lite/pom.xml
  protobuf-maven-plugin/src/it/java-test/pom.xml
  protobuf-maven-plugin/src/it/kotlin-main/pom.xml
  protobuf-maven-plugin/src/it/kotlin-test/pom.xml
  protobuf-maven-plugin/src/it/path-protoc/pom.xml
  protobuf-maven-plugin/src/it/reactor-grpc-binary-plugin/pom.xml
  protobuf-maven-plugin/src/it/reactor-grpc-jvm-plugin/pom.xml
  protobuf-maven-plugin/src/it/scalapb-plugin/pom.xml
  protobuf-maven-plugin/src/it/skip/pom.xml
  protobuf-maven-plugin/src/it/test-dependency-resolution/pom.xml
  protobuf-maven-plugin/src/site/markdown/usage.md
  protobuf-maven-plugin/src/site/markdown/user-guides/basic-usage.md
  scripts/install-protoc-to-github-runner.sh
Labels: documentation, integration-tests

#331 Update Maven to 3.9.9
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: techdebt

#332 GH-327: Report offending paths when failing to open ZIP archives
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoArchiveExtractor.java
Labels: bug, techdebt

#335 GH-327: Cleanup tasks
  protobuf-maven-plugin/src/it/gh-327-non-zip-archive-handling/invoker.properties
  protobuf-maven-plugin/src/it/gh-327-non-zip-archive-handling/pom.xml
  protobuf-maven-plugin/src/it/gh-327-non-zip-archive-handling/selector.groovy
  protobuf-maven-plugin/src/it/gh-327-non-zip-archive-handling/src/main/protobuf/org/example/helloworld.proto
  protobuf-maven-plugin/src/it/gh-327-non-zip-archive-handling/test.groovy
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoSourceResolver.java
Labels: techdebt, integration-tests

#337 GH-334: remove duplicate "--proto_path" logs
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceCodeGenerator.java
Labels: bug, techdebt

#342 Improve formatting of generated scripts in JvmPluginResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
Labels: techdebt

#343 feat: improved jvm plugin subprocess handling
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
Labels: techdebt

#352 GH-351: Replace Component annotations with javax.inject.Inject.
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
Labels: dependencies, techdebt

#353 GH-312: Move solution into HostSystem class and add unit tests
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/HostSystemTest.java
Labels: tests

#354 Update to protobuf 4.28.0
  README.md
  protobuf-maven-plugin/src/it/embed-main-sources/pom.xml
  protobuf-maven-plugin/src/it/gh-132-duplicate-maven-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-132-duplicate-maven-dependencies/some-project/pom.xml
  protobuf-maven-plugin/src/it/gh-135-compile-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-164-direct-dependency-resolution-depth-for-source-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-164-transitive-dependency-resolution-depth-for-source-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-250-excludes/pom.xml
  protobuf-maven-plugin/src/it/gh-250-includes/pom.xml
  protobuf-maven-plugin/src/it/gh-267-resolve-test-jar-type/pom.xml
  protobuf-maven-plugin/src/it/gh-267-resolve-tests-classifier/pom.xml
  protobuf-maven-plugin/src/it/gh-277-plugin-ordering/pom.xml
  protobuf-maven-plugin/src/it/gh-299-ehcache-jaxb-resolution-failure/pom.xml
  protobuf-maven-plugin/src/it/gh-302-runtime-scope-direct-resolution/pom.xml
  protobuf-maven-plugin/src/it/gh-302-runtime-scope-transitive-resolution/pom.xml
  protobuf-maven-plugin/src/it/gh-327-non-zip-archive-handling/pom.xml
  protobuf-maven-plugin/src/it/grpc-plugin/pom.xml
  protobuf-maven-plugin/src/it/java-main-empty/pom.xml
  protobuf-maven-plugin/src/it/java-main-lite/pom.xml
  protobuf-maven-plugin/src/it/java-main/pom.xml
  protobuf-maven-plugin/src/it/java-paths/pom.xml
  protobuf-maven-plugin/src/it/java-test-empty/pom.xml
  protobuf-maven-plugin/src/it/java-test-lite/pom.xml
  protobuf-maven-plugin/src/it/java-test/pom.xml
  protobuf-maven-plugin/src/it/kotlin-main/pom.xml
  protobuf-maven-plugin/src/it/kotlin-test/pom.xml
  protobuf-maven-plugin/src/it/path-protoc/pom.xml
  protobuf-maven-plugin/src/it/reactor-grpc-binary-plugin/pom.xml
  protobuf-maven-plugin/src/it/reactor-grpc-jvm-plugin/pom.xml
  protobuf-maven-plugin/src/it/scalapb-plugin/pom.xml
  protobuf-maven-plugin/src/it/skip/pom.xml
  protobuf-maven-plugin/src/it/test-dependency-resolution/pom.xml
  protobuf-maven-plugin/src/site/markdown/usage.md
  protobuf-maven-plugin/src/site/markdown/user-guides/basic-usage.md
Labels: dependencies, tests
