Repository ascopes/protobuf-maven-plugin, pull requests merged in 2024-06, with the labels that each got.

#240 Simplify platform classifier selection process
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/PlatformClassifierFactory.java
Labels: internal improvement

#241 Calculate the User-Agent for URL connections on startup
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/UrlResourceFetcher.java
Labels: internal improvement

#245 Update protoc examples to use protobuf 4.27.1
  README.md
  protobuf-maven-plugin/src/it/embed-main-sources/pom.xml
  protobuf-maven-plugin/src/it/gh-132-duplicate-maven-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-132-duplicate-maven-dependencies/some-project/pom.xml
  protobuf-maven-plugin/src/it/gh-135-compile-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-164-direct-dependency-resolution-depth-for-source-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-164-transitive-dependency-resolution-depth-for-source-dependencies/pom.xml
  protobuf-maven-plugin/src/it/grpc-plugin/pom.xml
  protobuf-maven-plugin/src/it/java-main-empty/pom.xml
  protobuf-maven-plugin/src/it/java-main-lite/pom.xml
  protobuf-maven-plugin/src/it/java-main/pom.xml
  protobuf-maven-plugin/src/it/java-paths/pom.xml
  protobuf-maven-plugin/src/it/java-test-empty/pom.xml
  protobuf-maven-plugin/src/it/java-test-lite/pom.xml
  protobuf-maven-plugin/src/it/java-test/pom.xml
  protobuf-maven-plugin/src/it/kotlin-main/pom.xml
  protobuf-maven-plugin/src/it/kotlin-test/pom.xml
  protobuf-maven-plugin/src/it/reactor-grpc-binary-plugin/pom.xml
  protobuf-maven-plugin/src/it/reactor-grpc-jvm-plugin/pom.xml
  protobuf-maven-plugin/src/it/scalapb-plugin/pom.xml
  protobuf-maven-plugin/src/it/skip/pom.xml
  protobuf-maven-plugin/src/site/markdown/index.md
Labels: integration-tests

#246 Improve Android detection
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/HostSystemTest.java
Labels: internal improvement

#247 Fix missing unit test report set on generated site
  protobuf-maven-plugin/pom.xml
  protobuf-maven-plugin/src/site/site.xml
Labels: documentation

#255 Make implicit javax.annotation dependency into an explicit one
  pom.xml
  protobuf-maven-plugin/pom.xml
Labels: bug

#256 Update to Maven 3.9.8
  .mvn/wrapper/maven-wrapper.properties
Labels: dependencies

#259 Inherit JAR/ZIP modified timestamps during content extraction
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoArchiveExtractor.java
Labels: internal improvement

#260 Disable some reports on the site
  protobuf-maven-plugin/pom.xml
Labels: documentation

#261 Refactor executor out into separate class that is individually testable
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoSourceResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/ConcurrentExecutor.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/MultipleFailuresException.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fixtures/RandomFixtures.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/ConcurrentExecutorTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/MultipleFailuresExceptionTest.java
Labels: internal improvement

#258 GH-250: Support inclusion and exclusion of source files based on globs
  .github/workflows/pages.yml
  pom.xml
  protobuf-maven-plugin/pom.xml
  protobuf-maven-plugin/src/it/gh-250-excludes/invoker.properties
  protobuf-maven-plugin/src/it/gh-250-excludes/pom.xml
  protobuf-maven-plugin/src/it/gh-250-excludes/src/main/protobuf/org/example/channel.proto
  protobuf-maven-plugin/src/it/gh-250-excludes/src/main/protobuf/org/example/message.proto
  protobuf-maven-plugin/src/it/gh-250-excludes/src/main/protobuf/org/example/user.proto
  protobuf-maven-plugin/src/it/gh-250-excludes/test.groovy
  protobuf-maven-plugin/src/it/gh-250-includes/invoker.properties
  protobuf-maven-plugin/src/it/gh-250-includes/pom.xml
  protobuf-maven-plugin/src/it/gh-250-includes/src/main/protobuf/org/example/channel.proto
  protobuf-maven-plugin/src/it/gh-250-includes/src/main/protobuf/org/example/message.proto
  protobuf-maven-plugin/src/it/gh-250-includes/src/main/protobuf/org/example/user.proto
  protobuf-maven-plugin/src/it/gh-250-includes/test.groovy
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/GenerationRequest.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceCodeGenerator.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoArchiveExtractor.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoFileFilter.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoFilePredicates.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoSourceResolver.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/sources/ProtoFilePredicatesTest.java
Labels: new feature, internal improvement

#263 Set up .gitattributes
  mvnw.cmd
Labels: internal improvement

#270 Add support for custom plugin code injection
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceCodeGenerator.java
Labels: new feature

#272 GH-271: Use explicit map of required path environment variable values
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/HostSystemTest.java
Labels: bug

#273 GH-271: Document path resolution rules
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
  protobuf-maven-plugin/src/site/markdown/index.md
Labels: documentation

#274 Improve logging in HostSystem for future diagnostics
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
Labels: internal improvement

#275 Tidy up AetherMavenArtifactPathResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
Labels: internal improvement

#276 Update deploy.yml to auto-rollback if deployment fails
  .github/workflows/deploy.yml
Labels: ci

#280 Run oldmaven CI on Java 22 as well
  .github/workflows/build.yml
Labels: ci

#282 Use the latest versions of protobuf, protoc, grpc-java, and reactor
  README.md
  protobuf-maven-plugin/src/it/embed-main-sources/pom.xml
  protobuf-maven-plugin/src/it/gh-132-duplicate-maven-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-132-duplicate-maven-dependencies/some-project/pom.xml
  protobuf-maven-plugin/src/it/gh-135-compile-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-164-direct-dependency-resolution-depth-for-source-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-164-transitive-dependency-resolution-depth-for-source-dependencies/pom.xml
  protobuf-maven-plugin/src/it/gh-250-excludes/pom.xml
  protobuf-maven-plugin/src/it/gh-250-includes/pom.xml
  protobuf-maven-plugin/src/it/gh-267-resolve-test-jar-type/pom.xml
  protobuf-maven-plugin/src/it/gh-267-resolve-tests-classifier/pom.xml
  protobuf-maven-plugin/src/it/gh-277-plugin-ordering/pom.xml
  protobuf-maven-plugin/src/it/grpc-plugin/pom.xml
  protobuf-maven-plugin/src/it/http-url-grpc-plugin/pom.xml
  protobuf-maven-plugin/src/it/java-main-empty/pom.xml
  protobuf-maven-plugin/src/it/java-main-lite/pom.xml
  protobuf-maven-plugin/src/it/java-main/pom.xml
  protobuf-maven-plugin/src/it/java-paths/pom.xml
  protobuf-maven-plugin/src/it/java-test-empty/pom.xml
  protobuf-maven-plugin/src/it/java-test-lite/pom.xml
  protobuf-maven-plugin/src/it/java-test/pom.xml
  protobuf-maven-plugin/src/it/kotlin-main/pom.xml
  protobuf-maven-plugin/src/it/kotlin-test/pom.xml
  protobuf-maven-plugin/src/it/reactor-grpc-binary-plugin/pom.xml
  protobuf-maven-plugin/src/it/reactor-grpc-jvm-plugin/pom.xml
  protobuf-maven-plugin/src/it/scalapb-plugin/pom.xml
  protobuf-maven-plugin/src/it/skip/pom.xml
  protobuf-maven-plugin/src/site/markdown/index.md
Labels: ci, integration-tests

#262 Fix typo in new draft documentation.
  protobuf-maven-plugin/src/site/markdown/installation.md
Labels: documentation
