Repository ascopes/protobuf-maven-plugin, pull requests merged in 2024-12, with the labels that each got.

#482 GH-481: Fix bug where large builds crash on Windows
  pom.xml
  protobuf-maven-plugin/pom.xml
  protobuf-maven-plugin/src/it/gh-481-command-length/invoker.properties
  protobuf-maven-plugin/src/it/gh-481-command-length/pom.xml
  protobuf-maven-plugin/src/it/gh-481-command-length/prebuild.groovy
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/CommandLineExecutor.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocArgumentFileBuilderBuilder.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/ArgumentFileBuilder.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/TeeWriter.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/ArgumentFileBuilderTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/TeeWriterTest.java
Labels: bug

#485 GH-481: Adhere to protoc argument file rules correctly
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/CommandLineExecutor.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/ArgumentFileBuilder.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/TeeWriter.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/ArgumentFileBuilderTest.java
Labels: bug, general improvements

#490 Short-circuit glob checks for SourceGlobFilter.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/SourceGlobFilter.java
Labels: general improvements

#496 Initial Aether tests
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherArtifactMapper.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/WildcardAwareDependencyTraverser.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolverTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/ProtobufMavenPluginRepositorySessionTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/WildcardAwareDependencyTraverserTest.java
Labels: general improvements

#499 Enable incremental compilation by default
  README.md
  pom.xml
  protobuf-maven-plugin/pom.xml
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/incremental/IncrementalCacheManager.java
  protobuf-maven-plugin/src/site/markdown/faster-builds.md
  protobuf-maven-plugin/src/site/markdown/known-issues.md
Labels: general improvements

#505 Remove custom entry class from IncrementalCacheManager.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/incremental/IncrementalCacheManager.java
Labels: general improvements

#504 Optimise IncrementalCacheManager.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/incremental/IncrementalCacheManager.java
Labels: general improvements

#506 Add configuration option to generate the binary proto descriptor
  CONTRIBUTING.md
  protobuf-maven-plugin/src/it/protoc-descriptor-file/invoker.properties
  protobuf-maven-plugin/src/it/protoc-descriptor-file/pom.xml
  protobuf-maven-plugin/src/it/protoc-descriptor-file/src/main/protobuf/helloworld.proto
  protobuf-maven-plugin/src/it/protoc-descriptor-file/test.groovy
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/GenerationRequest.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocArgumentFileBuilderBuilder.java
  protobuf-maven-plugin/src/site/markdown/basic-usage.md
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
Labels: new feature

#508 Fix regression for Maven 3.8.2 in v2.9.0
  .github/workflows/build.yml
  protobuf-maven-plugin/src/it/protoc-descriptor-file/pom.xml
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
Labels: bug

#509 Improve ProtocResolver.java warnings
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
Labels: general improvements
