Repository ascopes/protobuf-maven-plugin, pull requests merged in 2025-01, with the labels that each got.

#516 Adds null check for descriptor file
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
Labels: bug

#517 Add support for proto descriptor options
  pom.xml
  protobuf-maven-plugin/pom.xml
  protobuf-maven-plugin/src/it/protoc-descriptor-file-options/invoker.properties
  protobuf-maven-plugin/src/it/protoc-descriptor-file-options/pom.xml
  protobuf-maven-plugin/src/it/protoc-descriptor-file-options/src/main/protobuf/helloworld.proto
  protobuf-maven-plugin/src/it/protoc-descriptor-file-options/test.groovy
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/GenerationRequest.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocArgumentFileBuilderBuilder.java
  protobuf-maven-plugin/src/site/markdown/basic-usage.md
  protobuf-maven-plugin/src/site/markdown/descriptor-files.md
  protobuf-maven-plugin/src/site/markdown/known-issues.md
  protobuf-maven-plugin/src/site/site.xml
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
Labels: bug, new feature

#526 Run CI on Maven 4
  .github/workflows/build.yml
  README.md
  pom.xml
Labels: general improvements

#530 Implement initial eclipse artifact mapper tests
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherArtifactMapper.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/FallbackEclipseArtifactType.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherArtifactMapperTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/FallbackEclipseArtifactTypeTest.java
Labels: tests

#533 GH-523: Relax prerequisite constraint to Maven 3.8 from 3.8.2
  .github/workflows/build.yml
  protobuf-maven-plugin/pom.xml
Labels: general improvements

#534 Improve Termux detection semantics
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/HostSystemTest.java
Labels: general improvements

#540 Improve quality of general logs
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/CommandLineExecutor.java
Labels: general improvements

#535 Defer coverage reports to the end of the CI pipeline
  .github/workflows/build.yml
  codecov.yml
Labels: tests
