Repository ascopes/protobuf-maven-plugin, pull requests merged in 2025-05, with the labels that each got.

#648 Use CDI for Aether components, add new unit tests
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherArtifactMapper.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherDependencyManagement.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/ProtobufMavenPluginRepositorySession.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/ScopeDependencyFilter.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherArtifactMapperTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherDependencyManagementTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolverTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/ProtobufMavenPluginRepositorySessionTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fixtures/RandomFixtures.java
Labels: chore

#649 Use a custom Plexus converter to defer URL parsing to the last minute
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/UriResourceFetcher.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/GenerationRequest.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/MainGenerateMojo.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/TestGenerateMojo.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/plexus/PathConverter.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/plexus/ProtobufMavenPluginConfigurator.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/plexus/UriConverter.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/plexus/package-info.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/BinaryPluginResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/UriProtocPlugin.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
  protobuf-maven-plugin/src/site/markdown/changing-protoc-versions.md
  protobuf-maven-plugin/src/site/markdown/using-protoc-plugins.md
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/UriResourceFetcherTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/plexus/PathConverterTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/plexus/UriConverterTest.java
Labels: chore

#651 Use Path instead of File for outputDescriptorFile parameter
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
Labels: chore

#653 Move various filesystem-related facilities to a dedicated package
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherArtifactMapper.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/fs/FileUtils.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/fs/TemporarySpace.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/fs/UriResourceFetcher.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/fs/package-info.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceRootRegistrar.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/BinaryPluginResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocExecutor.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoSourceResolver.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/filter/ProtoFileFilter.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/incremental/IncrementalCacheManager.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/SystemPathBinaryResolver.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fs/FileUtilsTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fs/TemporarySpaceTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fs/UriResourceFetcherTest.java
Labels: chore

#655 Hook up a ZIP protocol handler for URLs
  pom.xml
  protobuf-maven-plugin/pom.xml
  protobuf-maven-plugin/src/it/scalapb-plugin/pom.xml
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/fs/UriResourceFetcher.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/fs/ZipUrlStreamHandlerProvider.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
  protobuf-maven-plugin/src/main/resources/META-INF/services/java.net.spi.URLStreamHandlerProvider
  protobuf-maven-plugin/src/site/markdown/using-protoc-plugins.md
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fs/ZipUrlStreamHandlerProviderTest.java
Labels: documentation, new feature, chore

#659 Omit javax.annotation-api in examples and documentation
  protobuf-maven-plugin/src/it/gh-277-plugin-ordering/pom.xml
  protobuf-maven-plugin/src/it/grpc-plugin/pom.xml
  protobuf-maven-plugin/src/it/http-url-grpc-plugin/pom.xml
  protobuf-maven-plugin/src/it/reactor-grpc-binary-plugin/pom.xml
  protobuf-maven-plugin/src/it/setup/pom.xml
  protobuf-maven-plugin/src/site/markdown/using-protoc-plugins.md
Labels: documentation, chore

#661 Generate changelogs for the site
  pom.xml
Labels: dependencies

#662 Revert "Generate changelogs for the site (#661)"
  pom.xml
Labels: chore

#670 Allow running in offline mode
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/MainGenerateMojo.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/TestGenerateMojo.java
Labels: chore

#674 Improve URL resolution semantics and behaviours
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/fs/UriResourceFetcher.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fs/UriResourceFetcherTest.java
Labels: bug, chore

#684 Correctly specify immutables getter prefixes
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/MavenExclusion.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/package-info.java
Labels: chore

#692 GH-687: Add src/main/proto and src/test/proto as directory roots for migration purposes
  pom.xml
  protobuf-maven-plugin/pom.xml
  protobuf-maven-plugin/src/it/java-main-legacy-source-directory/invoker.properties
  protobuf-maven-plugin/src/it/java-main-legacy-source-directory/pom.xml
  protobuf-maven-plugin/src/it/java-main-legacy-source-directory/src/main/proto/helloworld.proto
  protobuf-maven-plugin/src/it/java-main-legacy-source-directory/src/test/java/org/example/helloworld/ProtobufTest.java
  protobuf-maven-plugin/src/it/java-main-legacy-source-directory/test.groovy
  protobuf-maven-plugin/src/it/java-test-legacy-source-directory/invoker.properties
  protobuf-maven-plugin/src/it/java-test-legacy-source-directory/pom.xml
  protobuf-maven-plugin/src/it/java-test-legacy-source-directory/src/test/java/org/example/helloworld/ProtobufTest.java
  protobuf-maven-plugin/src/it/java-test-legacy-source-directory/src/test/proto/helloworld.proto
  protobuf-maven-plugin/src/it/java-test-legacy-source-directory/test.groovy
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/MainGenerateMojo.java
  protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/TestGenerateMojo.java
  protobuf-maven-plugin/src/site/markdown/basic-usage.md
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/MainGenerateMojoTest.java
  protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/TestGenerateMojoTest.java
Labels: new feature
